[package]
name = "tilemap"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
map-macro = "0.2.4"
svgbobdoc = "0.2"
